"use client";
import {useEffect,useState} from "react";
import {useUserClock} from "@/components/layout/user-clock";
import {Notification,NotificationSettings,Reminder} from "@/lib/notifications";
import {getNotifications,getNotificationSettings,getReminders,saveReminder,cancelReminder,markNotificationRead,saveNotificationSettings} from "@/lib/actions/reminders";
import {getCalendar} from "@/lib/actions/calendar";
import {CalendarData} from "@/lib/calendar";
import {localDateTime,localDateTimeToUtc} from "@/lib/timezone";
import {enableBrowserPush} from "@/lib/push-browser";
export function NotificationCenter(){
 const {timeZone,tomorrow}=useUserClock();const [notifications,setNotifications]=useState<Notification[]>([]),[reminders,setReminders]=useState<Reminder[]>([]),[settings,setSettings]=useState<NotificationSettings>({enabled:false,daily_time:null,friend_activity:false,nudges:true}),[calendar,setCalendar]=useState<CalendarData>({tasks:[],habits:[],commitments:[]}),[editing,setEditing]=useState<Reminder|"new"|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const [n,r,s,c]=await Promise.all([getNotifications(),getReminders(),getNotificationSettings(),getCalendar()]);setNotifications(n);setReminders(r);setSettings(s);setCalendar(c)}
 useEffect(()=>{let live=true;Promise.all([getNotifications(),getReminders(),getNotificationSettings(),getCalendar()]).then(([n,r,s,c])=>{if(live){setNotifications(n);setReminders(r);setSettings(s);setCalendar(c)}}).catch(e=>{if(live)setError(e.message)});const timer=setInterval(()=>{void load().catch(()=>{})},60000);return()=>{live=false;clearInterval(timer)}},[]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError("");try{await action();await load();setEditing(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">Notifications</h1><button className="proof-action" onClick={()=>setEditing("new")}>Add reminder</button></header>
 {error&&<p role="alert" className="text-proof-red">{error}</p>}
 <section className="proof-panel space-y-4 p-4"><h2 className="text-lg font-bold">Notification settings</h2><p className="text-sm text-white/55">Times use {timeZone}. Push previews stay generic; open DailyProof to read the details.</p>
 <button disabled={busy} className="proof-action" onClick={()=>void run(async()=>{await enableBrowserPush();await saveNotificationSettings({...settings,enabled:true})})}>Enable push on this device</button>
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>saveNotificationSettings({enabled:f.get("enabled")==="on",nudges:f.get("nudges")==="on",friend_activity:f.get("friend_activity")==="on",daily_time:String(f.get("daily_time"))||null}))}} key={JSON.stringify(settings)}>
 {(["enabled","friend_activity","nudges"] as const).map((field,i)=><label key={field} className="flex min-h-11 items-center gap-3 text-sm"><input name={field} type="checkbox" defaultChecked={settings[field]} className="h-5 w-5"/>{["Push notifications enabled","Friend activity","Friend nudges"][i]}</label>)}
 <label className="proof-field">DailyProof reminder time (optional)<input type="time" name="daily_time" defaultValue={settings.daily_time?.slice(0,5)??""}/></label><button disabled={busy} className="proof-action">Save settings</button></form></section>
 {editing&&<form key={editing==="new"?"new":editing.id} className="proof-panel space-y-4 p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>saveReminder(editing==="new"?null:editing.id,{title:String(f.get("title")),message:String(f.get("message")),scheduled_at:localDateTimeToUtc(String(f.get("time")),timeZone)!,task_id:String(f.get("task"))||null,habit_id:String(f.get("habit"))||null,only_if_incomplete:f.get("conditional")==="on"}))}}>
 <h2 className="font-bold">{editing==="new"?"New reminder":"Edit reminder"}</h2><label className="proof-field">Title<input required maxLength={200} name="title" defaultValue={editing==="new"?"":editing.title}/></label><label className="proof-field">Message<textarea name="message" maxLength={2000} defaultValue={editing==="new"?"":editing.message}/></label>
 <label className="proof-field">Remind at<input name="time" type="datetime-local" required defaultValue={editing==="new"?`${tomorrow}T09:00`:localDateTime(editing.scheduled_at,timeZone)}/></label>
 <label className="proof-field">Task (optional)<select name="task" defaultValue={editing==="new"?"":editing.task_id??""}><option value="">No task</option>{calendar.tasks.filter(t=>t.status==="pending").map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>
 <label className="proof-field">Habit (optional)<select name="habit" defaultValue={editing==="new"?"":editing.habit_id??""}><option value="">No habit</option>{calendar.habits.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label>
 <label className="flex min-h-11 items-center gap-3 text-sm"><input name="conditional" type="checkbox" defaultChecked={editing==="new"?false:editing.only_if_incomplete} className="h-5 w-5"/>Only if the linked activity is incomplete</label>
 <div className="flex gap-2"><button disabled={busy} className="proof-action">Save reminder</button><button type="button" className="proof-action" onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 <section className="space-y-3"><h2 className="text-lg font-bold">Reminders</h2>{reminders.map(r=><article key={r.id} className="proof-panel space-y-2 p-4"><h3 className="break-words font-bold">{r.title}</h3><p className="text-sm text-white/55">{localDateTime(r.scheduled_at,timeZone).replace("T"," ")} · {r.status}</p>{r.status==="pending"&&<div className="flex gap-2"><button className="proof-action" onClick={()=>setEditing(r)}>Edit</button><button disabled={busy} className="proof-action" onClick={()=>void run(()=>cancelReminder(r.id))}>Cancel reminder</button></div>}</article>)}</section>
 <section className="space-y-3"><h2 className="text-lg font-bold">History</h2>{notifications.map(n=><article key={n.id} className="proof-panel space-y-2 p-4"><h3 className="break-words font-bold">{n.title}</h3><p className="whitespace-pre-wrap break-words text-sm text-white/70">{n.body}</p><p className="text-xs text-white/45">{localDateTime(n.created_at,timeZone).replace("T"," ")} · Push {n.push_status}</p>{n.error&&<p className="text-sm text-proof-amber">{n.error}</p>}{!n.read_at&&<button disabled={busy} className="proof-action" onClick={()=>void run(()=>markNotificationRead(n.id))}>Mark read</button>}</article>)}{notifications.length===0&&<p className="text-sm text-white/45">No notifications yet.</p>}</section>
 </div>;
}
