"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {FriendSummaryResult} from "@/lib/friend-summary";
import {shiftDateKey} from "@/lib/timezone";
import {proofImageUrl} from "@/lib/actions/proofs";
import {Proof} from "@/lib/proofs";
export function FriendHistory({userId}:{userId:string}){
 const [days,setDays]=useState<FriendSummaryResult[]>([]),[proofs,setProofs]=useState<Proof[]>([]),[open,setOpen]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let live=true;const db=createClient();db.rpc("get_friend_day_summary",{p_target_user_id:userId}).then(({data,error})=>{if(live){if(error)setError("Summary unavailable.");else setDays([data as FriendSummaryResult])}});return()=>{live=false}},[userId]);
 async function show(){setError("");if(open){setOpen(false);setDays(days.slice(0,1));setProofs([]);return}try{const db=createClient();const {data:today,error}=await db.rpc("get_friend_day_summary",{p_target_user_id:userId});if(error||!today)throw new Error("Summary unavailable.");const history=await Promise.all(Array.from({length:7},async(_,i)=>{const {data,error}=await db.rpc("get_friend_day_summary",{p_target_user_id:userId,p_target_date:shiftDateKey(today.today_key,-i)});if(error)throw new Error("History unavailable.");return data as FriendSummaryResult}));const {data:shared,error:proofError}=await db.from("proofs").select("id,user_id,type,content,storage_path,visibility,created_at").eq("user_id",userId).order("created_at",{ascending:false}).limit(20);if(proofError)throw new Error("Unable to load shared proof.");setDays(history);setProofs(shared??[]);setOpen(true)}catch(e){setError((e as Error).message)}}
 return <div className="space-y-2"><button onClick={()=>void show()} className="proof-action">{open?"Hide recent days":"View recent days"}</button>{error&&<p role="alert" className="text-sm text-proof-red">{error}</p>}{days.map(d=><div key={d.log_date} className="text-sm text-white/65"><p>{d.log_date}: {d.completion}% · {d.complete_count}/{d.total_count} · {d.streak} day streak</p>{open&&d.details_visible&&d.statuses?.map((s,i)=><p key={i} className="mt-1 break-words text-xs">{s.habit_name}: {s.status}</p>)}</div>)}{open&&proofs.map(p=><div key={p.id} className="rounded-xl border border-white/10 p-3">{p.type==="note"?<p className="whitespace-pre-wrap break-words text-sm">{p.content}</p>:p.type==="link"?<a href={p.content!} target="_blank" rel="noopener noreferrer" className="proof-action">Shared proof link</a>:<button className="proof-action" onClick={async()=>{try{window.open(await proofImageUrl(p.id),"_blank","noopener,noreferrer")}catch{setError("Proof is no longer available.")}}}>Open shared image</button>}</div>)}</div>;
}
